# Generated by Django 4.2.7 on 2023-12-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_alter_event_second_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='birthdate',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='anniversary_date',
        ),
        migrations.AddField(
            model_name='event',
            name='is_anniversary',
            field=models.BooleanField(default=False),
        ),
    ]
