# Generated by Django 4.2.7 on 2023-12-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_rename_birthdate_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'Decemeber')], default=1),
            preserve_default=False,
        ),
    ]
